{"level":"error","message":"Error al enviar mensaje a string: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at pptr://__puppeteer_evaluation_script__:2:42","stack":"Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at pptr://__puppeteer_evaluation_script__:2:42\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async Client.sendMessage (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/Client.js:935:28)\n    at async WhatsAppService.sendMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:61:21)\n    at async BotController.handleMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:14:5)\n    at async file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/routes/botRoutes.js:54:3","timestamp":"2025-04-02T00:53:18.599Z"}
{"level":"error","message":"Error en el controlador del bot: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at pptr://__puppeteer_evaluation_script__:2:42","stack":"Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at pptr://__puppeteer_evaluation_script__:2:42\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async Client.sendMessage (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/Client.js:935:28)\n    at async WhatsAppService.sendMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:61:21)\n    at async BotController.handleMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:14:5)\n    at async file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/routes/botRoutes.js:54:3","timestamp":"2025-04-02T00:53:18.600Z"}
{"level":"error","message":"Error al enviar mensaje a string: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at pptr://__puppeteer_evaluation_script__:2:42","stack":"Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at pptr://__puppeteer_evaluation_script__:2:42\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async Client.sendMessage (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/Client.js:935:28)\n    at async WhatsAppService.sendMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:61:21)\n    at async BotController.handleMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:14:5)\n    at async file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/routes/botRoutes.js:54:3","timestamp":"2025-04-02T00:53:20.965Z"}
{"level":"error","message":"Error en el controlador del bot: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at pptr://__puppeteer_evaluation_script__:2:42","stack":"Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at pptr://__puppeteer_evaluation_script__:2:42\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async Client.sendMessage (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/Client.js:935:28)\n    at async WhatsAppService.sendMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:61:21)\n    at async BotController.handleMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:14:5)\n    at async file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/routes/botRoutes.js:54:3","timestamp":"2025-04-02T00:53:20.966Z"}
{"level":"error","message":"Error al enviar mensaje a test: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at pptr://__puppeteer_evaluation_script__:2:42","stack":"Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at pptr://__puppeteer_evaluation_script__:2:42\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async Client.sendMessage (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/Client.js:935:28)\n    at async WhatsAppService.sendMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:61:21)\n    at async BotController.handleMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:14:5)\n    at async file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/routes/botRoutes.js:54:3","timestamp":"2025-04-02T00:56:58.360Z"}
{"level":"error","message":"Error en el controlador del bot: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at pptr://__puppeteer_evaluation_script__:2:42","stack":"Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at pptr://__puppeteer_evaluation_script__:2:42\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async Client.sendMessage (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/Client.js:935:28)\n    at async WhatsAppService.sendMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:61:21)\n    at async BotController.handleMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:14:5)\n    at async file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/routes/botRoutes.js:54:3","timestamp":"2025-04-02T00:56:58.360Z"}
{"level":"error","message":"Error al enviar mensaje a test: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at pptr://__puppeteer_evaluation_script__:2:42","stack":"Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at pptr://__puppeteer_evaluation_script__:2:42\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async Client.sendMessage (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/Client.js:935:28)\n    at async WhatsAppService.sendMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:64:21)\n    at async BotController.handleMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:14:5)\n    at async file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/routes/botRoutes.js:54:3","timestamp":"2025-04-02T00:59:05.951Z"}
{"level":"error","message":"Error en el controlador del bot: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at pptr://__puppeteer_evaluation_script__:2:42","stack":"Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at pptr://__puppeteer_evaluation_script__:2:42\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async Client.sendMessage (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/Client.js:935:28)\n    at async WhatsAppService.sendMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:64:21)\n    at async BotController.handleMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:14:5)\n    at async file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/routes/botRoutes.js:54:3","timestamp":"2025-04-02T00:59:05.951Z"}
{"level":"error","message":"Error al inicializar el cliente: Protocol error (Runtime.callFunctionOn): Target closed.","name":"ProtocolError","originalMessage":"","stack":"ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async JSHandle.evaluateHandle (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/JSHandle.js:97:16)\n    at async WaitTask.rerun (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:114:28)","timestamp":"2025-04-02T01:01:22.914Z"}
{"level":"error","message":"Error al inicializar el cliente: Navigation failed because browser has disconnected!","stack":"Error: Navigation failed because browser has disconnected!\n    at new LifecycleWatcher (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:95:223)\n    at Frame.goto (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Frame.js:204:25)\n    at CDPPage.goto (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:1083:91)\n    at Client.initialize (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/Client.js:323:20)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async WhatsAppService.initializeClient (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:79:4)\n    at async WhatsAppService.sendMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:97:5)\n    at async BotController.handleMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:14:5)\n    at async file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/routes/botRoutes.js:54:3","timestamp":"2025-04-02T01:01:27.918Z"}
{"level":"error","message":"Se alcanzó el número máximo de intentos de inicialización","timestamp":"2025-04-02T01:01:32.919Z"}
{"level":"error","message":"Error al enviar mensaje a string: El cliente de WhatsApp no está listo después de reinicializar","stack":"Error: El cliente de WhatsApp no está listo después de reinicializar\n    at WhatsAppService.sendMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:106:12)\n    at async BotController.handleMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:14:5)\n    at async file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/routes/botRoutes.js:54:3","timestamp":"2025-04-02T01:01:37.924Z"}
{"level":"error","message":"Error en el controlador del bot: El cliente de WhatsApp no está listo después de reinicializar","stack":"Error: El cliente de WhatsApp no está listo después de reinicializar\n    at WhatsAppService.sendMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:106:12)\n    at async BotController.handleMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:14:5)\n    at async file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/routes/botRoutes.js:54:3","timestamp":"2025-04-02T01:01:37.925Z"}
{"level":"error","message":"Error durante la inicialización: Protocol error (Runtime.callFunctionOn): Target closed.","name":"ProtocolError","originalMessage":"","stack":"ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)","timestamp":"2025-04-02T01:04:37.286Z"}
{"level":"error","message":"Error al inicializar el cliente: Protocol error (Runtime.callFunctionOn): Target closed.","name":"ProtocolError","originalMessage":"","stack":"ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)","timestamp":"2025-04-02T01:04:37.287Z"}
{"level":"error","message":"Error durante la inicialización: Protocol error (Runtime.callFunctionOn): Target closed.","name":"ProtocolError","originalMessage":"","stack":"ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async JSHandle.evaluateHandle (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/JSHandle.js:97:16)\n    at async WaitTask.rerun (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:114:28)","timestamp":"2025-04-02T01:05:56.669Z"}
{"level":"error","message":"Error al inicializar el cliente: Protocol error (Runtime.callFunctionOn): Target closed.","name":"ProtocolError","originalMessage":"","stack":"ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async JSHandle.evaluateHandle (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/JSHandle.js:97:16)\n    at async WaitTask.rerun (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:114:28)","timestamp":"2025-04-02T01:05:56.669Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:23:24.390Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:23:25.627Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:23:28.191Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:23:44.132Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:23:47.397Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:25:35.019Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:25:53.014Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:28:32.079Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:29:19.508Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:30:16.791Z"}
{"level":"error","message":"Error durante la inicialización: Timeout durante la inicialización del cliente","stack":"Error: Timeout durante la inicialización del cliente\n    at Timeout._onTimeout (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:151:29)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","timestamp":"2025-04-02T01:33:16.794Z"}
{"level":"error","message":"Error al inicializar el cliente: Timeout durante la inicialización del cliente","stack":"Error: Timeout durante la inicialización del cliente\n    at Timeout._onTimeout (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:151:29)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","timestamp":"2025-04-02T01:33:16.795Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:35:18.052Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:35:18.052Z"}
{"level":"error","message":"El servicio de Google Gemini no está inicializado","timestamp":"2025-04-02T01:35:29.271Z"}
{"level":"error","message":"El servicio de Google Gemini no está inicializado","timestamp":"2025-04-02T01:35:31.574Z"}
{"level":"error","message":"El servicio de Google Gemini no está inicializado","timestamp":"2025-04-02T01:35:35.303Z"}
{"level":"error","message":"Error durante la inicialización: Timeout durante la inicialización del cliente","stack":"Error: Timeout durante la inicialización del cliente\n    at Timeout._onTimeout (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:151:29)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","timestamp":"2025-04-02T01:38:18.084Z"}
{"level":"error","message":"Error al inicializar el cliente: Timeout durante la inicialización del cliente","stack":"Error: Timeout durante la inicialización del cliente\n    at Timeout._onTimeout (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:151:29)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","timestamp":"2025-04-02T01:38:18.085Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:41:13.384Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:41:13.384Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:41:46.550Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:41:46.554Z"}
{"level":"error","message":"Error durante la inicialización: Protocol error (Runtime.callFunctionOn): Execution context was destroyed.","name":"ProtocolError","originalMessage":"Execution context was destroyed.","stack":"ProtocolError: Protocol error (Runtime.callFunctionOn): Execution context was destroyed.\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)","timestamp":"2025-04-02T01:41:52.387Z"}
{"level":"error","message":"Error al inicializar el cliente: Protocol error (Runtime.callFunctionOn): Execution context was destroyed.","name":"ProtocolError","originalMessage":"Execution context was destroyed.","stack":"ProtocolError: Protocol error (Runtime.callFunctionOn): Execution context was destroyed.\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)","timestamp":"2025-04-02T01:41:52.388Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:42:13.375Z"}
{"level":"error","message":"Error durante la inicialización: Timeout durante la inicialización del cliente","stack":"Error: Timeout durante la inicialización del cliente\n    at Timeout._onTimeout (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:151:29)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","timestamp":"2025-04-02T01:45:13.378Z"}
{"level":"error","message":"Error al inicializar el cliente: Timeout durante la inicialización del cliente","stack":"Error: Timeout durante la inicialización del cliente\n    at Timeout._onTimeout (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:151:29)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","timestamp":"2025-04-02T01:45:13.379Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:47:11.683Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:47:34.092Z"}
{"level":"error","message":"GEMINI_API_KEY no está configurada en las variables de entorno","timestamp":"2025-04-02T01:50:01.122Z"}
{"errorDetails":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"description":"Invalid JSON payload received. Unknown name \"responseType\" at 'generation_config': Cannot find field.","field":"generation_config"}]}],"level":"error","message":"Error al generar respuesta con Google Gemini: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite-preview-02-05:generateContent: [400 Bad Request] Invalid JSON payload received. Unknown name \"responseType\" at 'generation_config': Cannot find field. [{\"@type\":\"type.googleapis.com/google.rpc.BadRequest\",\"fieldViolations\":[{\"field\":\"generation_config\",\"description\":\"Invalid JSON payload received. Unknown name \\\"responseType\\\" at 'generation_config': Cannot find field.\"}]}]","stack":"Error: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite-preview-02-05:generateContent: [400 Bad Request] Invalid JSON payload received. Unknown name \"responseType\" at 'generation_config': Cannot find field. [{\"@type\":\"type.googleapis.com/google.rpc.BadRequest\",\"fieldViolations\":[{\"field\":\"generation_config\",\"description\":\"Invalid JSON payload received. Unknown name \\\"responseType\\\" at 'generation_config': Cannot find field.\"}]}]\n    at handleResponseNotOk (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/@google/generative-ai/dist/index.mjs:432:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async makeRequest (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/@google/generative-ai/dist/index.mjs:401:9)\n    at async generateContent (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/@google/generative-ai/dist/index.mjs:865:22)\n    at async ChatSession.sendMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/@google/generative-ai/dist/index.mjs:1203:9)\n    at async AIService.generateResponse (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/aiService.js:136:19)\n    at async BotController.processMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:30:21)\n    at async BotController.handleMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:13:21)\n    at async WhatsAppService.handleIncomingMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:191:4)\n    at async Client.<anonymous> (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:141:6)","status":400,"statusText":"Bad Request","timestamp":"2025-04-02T01:59:19.722Z"}
{"level":"error","message":"Error al generar respuesta con Google Gemini: [GoogleGenerativeAI Error]: Content should have 'parts' property with an array of Parts","stack":"Error: [GoogleGenerativeAI Error]: Content should have 'parts' property with an array of Parts\n    at validateChatHistory (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/@google/generative-ai/dist/index.mjs:1056:19)\n    at new ChatSession (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/@google/generative-ai/dist/index.mjs:1147:13)\n    at GenerativeModel.startChat (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/@google/generative-ai/dist/index.mjs:1394:16)\n    at AIService.generateResponse (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/aiService.js:131:23)\n    at BotController.processMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:30:37)\n    at BotController.handleMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:13:32)\n    at WhatsAppService.handleIncomingMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:191:24)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Client.<anonymous> (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:141:6)","timestamp":"2025-04-02T02:02:00.003Z"}
{"errorDetails":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"description":"Invalid JSON payload received. Unknown name \"responseType\" at 'generation_config': Cannot find field.","field":"generation_config"}]}],"level":"error","message":"Error al generar respuesta con Google Gemini: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite-preview-02-05:generateContent: [400 Bad Request] Invalid JSON payload received. Unknown name \"responseType\" at 'generation_config': Cannot find field. [{\"@type\":\"type.googleapis.com/google.rpc.BadRequest\",\"fieldViolations\":[{\"field\":\"generation_config\",\"description\":\"Invalid JSON payload received. Unknown name \\\"responseType\\\" at 'generation_config': Cannot find field.\"}]}]","stack":"Error: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite-preview-02-05:generateContent: [400 Bad Request] Invalid JSON payload received. Unknown name \"responseType\" at 'generation_config': Cannot find field. [{\"@type\":\"type.googleapis.com/google.rpc.BadRequest\",\"fieldViolations\":[{\"field\":\"generation_config\",\"description\":\"Invalid JSON payload received. Unknown name \\\"responseType\\\" at 'generation_config': Cannot find field.\"}]}]\n    at handleResponseNotOk (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/@google/generative-ai/dist/index.mjs:432:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async makeRequest (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/@google/generative-ai/dist/index.mjs:401:9)\n    at async generateContent (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/@google/generative-ai/dist/index.mjs:865:22)\n    at async ChatSession.sendMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/@google/generative-ai/dist/index.mjs:1203:9)\n    at async AIService.generateResponse (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/aiService.js:154:19)\n    at async BotController.processMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:30:21)\n    at async BotController.handleMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/controllers/botController.js:13:21)\n    at async WhatsAppService.handleIncomingMessage (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:191:4)\n    at async Client.<anonymous> (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:141:6)","status":400,"statusText":"Bad Request","timestamp":"2025-04-02T02:27:35.548Z"}
{"level":"error","message":"Error durante la inicialización: Timeout durante la inicialización del cliente","stack":"Error: Timeout durante la inicialización del cliente\n    at Timeout._onTimeout (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:152:29)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","timestamp":"2025-04-02T03:52:28.157Z"}
{"level":"error","message":"Error al inicializar el cliente: Timeout durante la inicialización del cliente","stack":"Error: Timeout durante la inicialización del cliente\n    at Timeout._onTimeout (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:152:29)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","timestamp":"2025-04-02T03:52:28.158Z"}
{"level":"error","message":"Error durante la inicialización: Protocol error (Runtime.callFunctionOn): Target closed.","name":"ProtocolError","originalMessage":"","stack":"ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)","timestamp":"2025-04-02T04:16:35.188Z"}
{"level":"error","message":"Error al inicializar el cliente: Protocol error (Runtime.callFunctionOn): Target closed.","name":"ProtocolError","originalMessage":"","stack":"ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)","timestamp":"2025-04-02T04:16:35.191Z"}
{"level":"error","message":"Error durante la inicialización: Protocol error (Runtime.callFunctionOn): Target closed.","name":"ProtocolError","originalMessage":"","stack":"ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async exposeFunctionIfAbsent (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/util/Puppeteer.js:14:19)\n    at async Client.inject (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/Client.js:176:9)\n    at async Client.initialize (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/Client.js:329:9)\n    at async WhatsAppService.initializeClient (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:206:5)","timestamp":"2025-04-02T04:22:13.343Z"}
{"level":"error","message":"Error al inicializar el cliente: Protocol error (Runtime.callFunctionOn): Target closed.","name":"ProtocolError","originalMessage":"","stack":"ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async exposeFunctionIfAbsent (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/util/Puppeteer.js:14:19)\n    at async Client.inject (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/Client.js:176:9)\n    at async Client.initialize (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/Client.js:329:9)\n    at async WhatsAppService.initializeClient (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:206:5)","timestamp":"2025-04-02T04:22:13.345Z"}
{"level":"error","message":"Error durante la inicialización: Protocol error (Runtime.callFunctionOn): Target closed.","name":"ProtocolError","originalMessage":"","stack":"ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)","timestamp":"2025-04-02T04:24:42.592Z"}
{"level":"error","message":"Error durante la inicialización: Protocol error (Runtime.callFunctionOn): Target closed.","name":"ProtocolError","originalMessage":"","stack":"ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)","timestamp":"2025-04-02T04:24:57.609Z"}
{"level":"error","message":"Error al inicializar el cliente: Protocol error (Runtime.callFunctionOn): Target closed.","name":"ProtocolError","originalMessage":"","stack":"ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)","timestamp":"2025-04-02T04:24:57.630Z"}
{"level":"error","message":"Error al inicializar el cliente: Protocol error (Runtime.callFunctionOn): Target closed.","name":"ProtocolError","originalMessage":"","stack":"ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24\n    at new Promise (<anonymous>)\n    at CDPSessionImpl.send (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)\n    at ExecutionContext._ExecutionContext_evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)\n    at async ExecutionContext.evaluate (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)","timestamp":"2025-04-02T04:25:12.619Z"}
{"level":"error","message":"Error al generar QR en base64: this.qrPromiseResolve is not a function","stack":"TypeError: this.qrPromiseResolve is not a function\n    at Client.qrCallback (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:487:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-04-02T04:33:11.382Z"}
{"level":"error","message":"Error al generar QR en base64: this.qrPromiseResolve is not a function","stack":"TypeError: this.qrPromiseResolve is not a function\n    at Client.qrCallback (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:490:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-04-02T04:53:40.446Z"}
{"level":"error","message":"Error al generar QR en base64: this.qrPromiseResolve is not a function","stack":"TypeError: this.qrPromiseResolve is not a function\n    at Client.qrCallback (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:490:12)\n    at Client.emit (node:events:526:35)\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/Client.js:151:22\n    at CDPPage._CDPPage_onBindingCalled (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:2462:30)\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:160:100\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:3:232\n    at Array.map (<anonymous>)\n    at Object.emit (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:3:216)\n    at CDPSessionImpl.emit (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:87:22)\n    at CDPSessionImpl._onMessage (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:350:18)\n    at Connection.onMessage (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:156:25)","timestamp":"2025-04-02T05:17:20.105Z"}
{"level":"error","message":"Error al generar QR en base64: this.qrPromiseResolve is not a function","stack":"TypeError: this.qrPromiseResolve is not a function\n    at Client.<anonymous> (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:162:11)\n    at Client.emit (node:events:514:28)\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/whatsapp-web.js/src/Client.js:151:22\n    at CDPPage._CDPPage_onBindingCalled (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:2462:30)\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:160:100\n    at /Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:3:232\n    at Array.map (<anonymous>)\n    at Object.emit (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:3:216)\n    at CDPSessionImpl.emit (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:87:22)\n    at CDPSessionImpl._onMessage (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:350:18)\n    at Connection.onMessage (/Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:156:25)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at listOnTimeout (node:internal/timers:540:9)\n    at process.processTimers (node:internal/timers:514:7)","timestamp":"2025-04-02T05:50:21.051Z"}
{"level":"error","message":"Error al generar QR en base64: this.qrPromiseResolve is not a function","stack":"TypeError: this.qrPromiseResolve is not a function\n    at Client.<anonymous> (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:161:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-04-02T06:00:35.521Z"}
{"level":"error","message":"Error al generar QR en base64: this.qrPromiseResolve is not a function","stack":"TypeError: this.qrPromiseResolve is not a function\n    at Client.<anonymous> (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:161:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-04-02T06:05:34.675Z"}
{"level":"error","message":"Error al generar QR en base64: this.qrPromiseResolve is not a function","stack":"TypeError: this.qrPromiseResolve is not a function\n    at Client.<anonymous> (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:161:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-04-02T21:48:45.260Z"}
{"level":"error","message":"Error generando QR: this.cleanupQrListeners is not a function","stack":"TypeError: this.cleanupQrListeners is not a function\n    at Client.qrHandler (file:///Users/pabloag/Desktop/DEV/19-02-2025/ws-services-glidpa/src/services/whatsappService.js:504:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-04-02T22:21:15.673Z"}
